---
dist: xenial
sudo: required

language: go
go:
  - "1.12.x"

go_import_path: github.com/ligato/vpp-agent

services:
  - docker

git:
  depth: 5
  submodules: false

cache:
  directories:
    - ${HOME}/.cache

install: true

stages:
  - Check
  - Test
  - Build
  - Integration
  - name: E2E
    if: /^force-e2e/

jobs:
  include:
    - stage: Check
      language: shell
      name: "Check formatting"
      addons:
        apt:
          packages:
            - npm
      script:
        - make yamllint
        - make check-links || true
    - name: "Go dependency check"
      script: make dep-check

    - stage: Test
      name: "Code linter"
      script: make lint
    - name: "Unit tests"
      script: make test-cover

    - stage: Build
      script:
        - make cmd
        - make examples

    - stage: Integration
      env: VPP_VERSION=1904
      script:
        - make verify-binapi
        - make integration-tests
    - env: VPP_VERSION=1908
      script:
        - make verify-binapi
        - make integration-tests
    - env: VPP_VERSION=2001
      script:
        - make verify-binapi
        - make integration-tests

    - stage: E2E
      env: VPP_VERSION=1904
      script:
        - make e2e-tests
    - env: VPP_VERSION=1908
      script:
        - make e2e-tests
    - env: VPP_VERSION=2001
      script:
        - make e2e-tests
